services:
  chalkops_valkey:
    image: valkey/valkey:7.2.5
    container_name: chalkops_valkey_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - chalkops_redis_cache_data:/data

  chalkops-db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - chalkops_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  chalkops_vault:
    image: hashicorp/vault:1.16.2
    container_name: chalkops_dev_vault
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
    ports:
      - "1234:1234"
    command: server -dev -dev-root-token-id=myroot -dev-listen-address=0.0.0.0:1234

volumes:
  chalkops_redis_cache_data: 
  chalkops_postgres_data:
